import os
import sys
import urllib.request
from tqdm import tqdm

# Add parent directory to path to import settings
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import settings

def download_crx(extension_id, output_dir):
    """
    Downloads a CRX file directly from Google's Web Store update URL.
    """
    url = f"https://clients2.google.com/service/update2/crx?response=redirect&prodversion=126.0&acceptformat=crx2,crx3&x=id%3d{extension_id}%26uc"
    
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, f"{extension_id}.crx")
    
    # Skip if already downloaded
    if os.path.exists(output_path):
        return True
        
    try:
        # Create a request object with a User-Agent to avoid 403s
        req = urllib.request.Request(
            url, 
            headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'}
        )
        with urllib.request.urlopen(req) as response, open(output_path, 'wb') as out_file:
            data = response.read()
            out_file.write(data)
        return True
    except Exception as e:
        print(f"Failed to download {extension_id}: {e}")
        return False

# A list of 500 popular extension IDs (Benign set)
# Extracted dynamically from popular Chrome Web Store extensions dataset
POPULAR_EXTENSIONS = [
    "aapbdbdomjkkjkaonfhkkikfgjllcleb",
    "jlhmfgmfgeifomenelglieieghnjghma",
    "gomekmidlodglbbmalcneegieacbdmki",
    "oocalimimngaihdkbihfgmpkcpnmlaoa",
    "dhdgffkkebhmkfjojejmpbldmpobfkfo",
    "bgnkhhnnamicmpeenaelnjfhikgbkllg",
    "mmeijimgabbpbgpdklnllpncmdofkcpn",
    "cfhdojbkjhnklbpkdaibdccddilifddb",
    "inomeogfingihgjfjlpeplalcfajhgai",
    "cjpalhdlnbpafiamejdnhcphjbkeiagm",
    "gighmmpiobklfepjocnamgkkbiglidom",
    "efaidnbmnnnibpcajpcglclefindmkaj",
    "ncennffkjdiamlpmcbajkmaiiiddgioo",
    "hdokiejnpimakedhajhdlcegeplioahd",
    "ppnbnpeolgkicgegkbkbjmhlideopiji",
    "eofcbnmajmjmplflapaojjnihcjkigck",
    "lifbcibllhkdhoafpjfnlhfpfgnpldfl",
    "kbfnbcaeplbcioakkpcpgfkobkghlhen",
    "bmnlcjabgnpnenekpadlanbbkooimhnj",
    "cmedhionkhpnakcndndgjdbohmhepckk",
    "ecnphlgnajanjnkcmbpancdjoidceilk",
    "gkojfkhlekighikafcpjkiklfbnlmeio",
    "gpdjojdkbbmdfjfahjcgigfpmkopogic",
    "nckgahadagoaajjgafhacjanaoiihapd",
    "lpcaedmchfhocbbapmcbpinfpgnhiddi",
    "dncepekefegjiljlfbihljgogephdhph",
    "kgjfgplpablkjnlkjmjdecgdpfankdle",
    "ihcjicgdanjaechkgeegckofjjedodee",
    "jjkchpdmjjdmalgembblgafllbpcjlei",
    "inoeonmfapjbbkmdafoankkfajkcphgd",
    "pbjikboenpfhbbejgkoklgkhjpfogcam",
    "glcimepnljoholdmjchkloafkggfoijh",
    "ogdlpmhglpejoiomcodnpjnfgcpmgale",
    "fkepacicchenbjecpbpbclokcabebhah",
    "flliilndjeohchalpbbcdekjklbdgfkk",
    "fdpohaocaechififmbbbbbknoalclacl",
    "nkbihfbeogaeaoehlefnkodbefgpgknn",
    "bihmplhobchoageeokmgbdihknkjbknd",
    "ifbmcpbgkhlpfcodhjhdbllhiaomkdej",
    "bkdgflcldnnnapblkhphbgpggdiikppg",
    "kjeghcllfecehndceplomkocgfbklffd",
    "bfgdeiadkckfbkeigkoncpdieiiefpig",
    "gmbmikajjgmnabiglmofipeabaddhgne",
    "iifchhfnnmpdbibifmljnfjhpififfog",
    "ajopnjidmegmdimjlfnijceegpefgped",
    "liecbddmkiiihnedobmlmillhodjkdmb",
    "fdcgdnkidjaadafnichfpabhfomcebme",
    "fdjamakpfbbddfjaooikfcpapjohcfmg",
    "dpdmhfocilnekecfjgimjdeckachfbec",
    "hehijbfgiekmjfkfjpbkbammjbdenadd",
    "caljgklbbfbcjjanaijlacgncafpegll",
    "admmjipmmciaobhojoghlmleefbicajg",
    "jgfbgkjjlonelmpenhpfeeljjlcgnkpe",
    "nopfnnpnopgmcnkjchnlpomggcdjfepo",
    "mbckjcfnjmoiinpgddefodcighgikkgn",
    "ndjpnladcallmjemlbaebfadecfhkepb",
    "feepmdlmhplaojabeoecaobfmibooaid",
    "eimadpbcbfnmbkopoojfekhnkhdbieeh",
    "kklailfgofogmmdlhgmjgenehkjoioip",
    "ooadnieabchijkibjpeieeliohjidnjj",
    "mihcahmgecmbnbcchbopgniflfhgnkff",
    "pioclpoplcdbaefihamjohnefbikjilc",
    "omghfjlpggmjjaagoclmmobgdodcjboh",
    "ohfgljdgelakfkefopgklcohadegdpjf",
    "ekhagklcjbdpajgpjgmbionohlpdbjgc",
    "glnpjglilkicbckjpbgcfkogebgllemb",
    "cifnddnffldieaamihfkhkdgnbhfmaci",
    "ccbpbkebodcjkknkfkpmfeciinhidaeh",
    "chhjbpecpncaggjpdakmflnfcopglcmi",
    "mcbpblocgmgfnpjjppndjkmgjaogfceg",
    "laookkfknpbbblfpciffpaejjkokdgca",
    "ldipcbpaocekfooobnbcddclnhejkcpn",
    "mgijmajocgfcbeboacabfgobmjgjcoja",
    "fjnbnpbmkenffdnngjfgmeleoegfcffe",
    "enfolipbjmnmleonhhebhalojdpcpdoo",
    "mclkkofklkfljcocdinagocijmpgbhab",
    "kejbdjndbnbjgmefkgdddjlbokphdefk",
    "mbniclmhobmnbdlbpiphghaielnnpgdp",
    "jmfikkaogpplgnfjmbjdpalkhclendgd",
    "gcbommkclmclpchllfjekcdonpmejbdp",
    "oofgbpoabipfcfjapgnbbjjaenockbdp",
    "kglhbbefdnlheedjiejgomgmfplipfeb",
    "fngmhnnpilhplaeedifhccceomclgfbg",
    "fmkadmapgofadopljbjfkapdkoienihi",
    "fdgfkebogiimcoedlicjlajpkdmockpc",
    "gohjpllcolmccldfdggmamodembldgpc",
    "hodiladlefdpcbemnbbcpclbmknkiaem",
    "bigefpfhnfcobdlfbedofhhaibnlghod",
    "niloccemoadcdkdjlinkgdfekeahmflj",
    "nlbejmccbhkncgokjcmghpfloaajcffj",
    "mlomiejdfkolichcflejclcbmpeaniij",
    "chphlpgkkbolifaimnlloiipkdnihall",
    "pdnfnkhpgegpcingjbfihlkjeighnddk",
    "bkkbcggnhapdmkeljlodobbkopceiche",
    "nffaoalbilbmmfgbnbgppjihopabppdk",
    "hjngolefdpdnooamgdldlkjgmdcmcjnc",
    "fcfhplploccackoneaefokcmbjfbkenj",
    "lmjnegcaeklhafolokijcfjliaokphfk",
    "klekeajafkkpokaofllcadenjdckhinm",
    "eedlgdlajadkbbjoobobefphmfkcchfk",
    "neebplgakaahbhdphmkckjjcegoiijjo",
    "ophjlpahpchlmihnnnihgmmeilfjmjjc",
    "bhlhnicpbhignbdhedgjhgdocnmhomnp",
    "pgjjikdiikihdfpoppgaidccahalehjh",
    "nlipoenfbbikpbjkfpfillcgkoblgpmj",
    "fbcohnmimjicjdomonkcbcpbpnhggkip",
    "bkpenclhmiealbebdopglffmfdiilejc",
    "jfbnmfgkohlfclfnplnlenbalpppohkm",
    "hbkpclpemjeibhioopcebchdmohaieln",
    "pbcgcpeifkdjijdjambaakmhhpkfgoec",
    "hkjemkcbndldepdbnbdnibeppofoooio",
    "dmpojjilddefgnhiicjcmhbkjgbbclob",
    "oakfpjifgmfpainopanfgfckhkcfgacb",
    "hkgfoiooedgoejojocmhlaklaeopbecg",
    "fllaojicojecljbmefodhfapmkghcbnh",
    "djflhoibgkdhkhhcedjiklpkjnoahfmg",
    "callobklhcbilhphinckomhgkigmfocg",
    "mhkhmbddkmdggbhaaaodilponhnccicb",
    "lkhjgdkpibcepflmlgahofcmeagjmecc",
    "mdanidgdpmkimeiiojknlnekblgmpdll",
    "pachckjkecffpdphbpmfolblodfkgbhl",
    "cjkkodhikogdenlfobgbhkggogejidim",
    "lmhkpmbekcpmknklioeibfkpmmfibljd",
    "bfbameneiokkgbdmiekhjnmfkcnldhhm",
    "bcjindcccaagfpapjjmafapmmgkkhgoa",
    "hmdcmlfkchdmnmnmheododdhjedfccka",
    "padekgcemlokbadohgkifijomclgjgif",
    "gbmdgpbipfallnflgajpaliibnhdgobh",
    "chklaanhfefbnpoihckbnefhakgolnmc",
    "gppongmhjkpfnbhagpmjfkannfbllamg",
    "nhdogjmejiglipccpnnnanhbledajbpd",
    "fadndhdgpmmaapbmfcknlfgcflmmmieb",
    "abjcfabbhafbcdfjoecdgepllmpfceif",
    "cgakmbkklpmijhckpolanjijghgfpeoa",
    "cnpniohnfphhjihaiiggeabnkjhpaldj",
    "ndnaehgpjlnokgebbaldlmgkapkpjkkb",
    "gjknjjomckknofjidppipffbpoekiipm",
    "edacconmaakjimmfgnblocblbcdcpbko",
    "oldceeleldhonbafppcapldpdifcinji",
    "dmghijelimhndkbmpgbldicpogfkceaj",
    "oeopbcgkkoapgobdbedcemjljbihmemj",
    "gojbdfnpnhogfdgjbigejoaolejmgdhk",
    "cmeakgjggjdlcpncigglobpjbkabhmjl",
    "eiimnmioipafcokbfikbljfdeojpcgbh",
    "hnmpcagpplmpfojmgmnngilcnanddlhb",
    "oemmndcbldboiebfnladdacbdfmadadm",
    "lgblnfidahcdcjddiepkckcfdhpknnjh",
    "dagcmkpagjlhakfdhnbomgmjdpkdklff",
    "eppjkefeiehhflmgkhdooajgbkkegpcl",
    "fjoaledfpmneenckfbpdfhkmimnjocfa",
    "bhghoamapcdpbohphigoooaddinpkbai",
    "aabcgdmkeabbnleenpncegpcngjpnjkc",
    "hlphpjodcfdblfmbbdjodbfmlonmidfh",
    "oijdcdmnjjgnnhgljmhkjlablaejfeeb",
    "klfbfknakjcihehkmalfgphojkhgmfcb",
    "aeblfdkhhhdcdjpifhhbdiojplfjncoa",
    "hgjdbeiflalimgifllheflljdconlbig",
    "hniebljpgcogalllopnjokppmgbhaden",
    "pkehgijcmpdhfbdbbnkijodmdjhbjlgp",
    "nngceckbapebfimnlniiiahkandclblb",
    "bgdpkilkheacbboffppjgceiplijhfpd",
    "hoombieeljmmljlkjmnheibnpciblicm",
    "ggjhpefgjjfobnfoldnjipclpcfbgbhl",
    "mjbepbhonbojpoaenhckjocchgfiaofo",
    "fjgncogppolhfdpijihbpfmeohpaadpc",
    "ahmpjcflkgiildlgicmcieglgoilbfdp",
    "kmffehbidlalibfeklaefnckpidbodff",
    "kbmfpngjjgdllneeigpgjifpgocmfgmb",
    "aleakchihdccplidncghkekgioiakgal",
    "dcngeagmmhegagicpcmpinaoklddcgon",
    "honjcnefekfnompampcpmcdadibmjhlk",
    "nikfmfgobenbhmocjaaboihbeocackld",
    "ghgabhipcejejjmhhchfonmamedcbeod",
    "fgddmllnllkalaagkghckoinaemmogpe",
    "bkbeeeffjjeopflfhgeknacdieedcoml",
    "pchfckkccldkbclgdepkaonamkignanh",
    "hbapdpeemoojbophdfndmlgdhppljgmp",
    "bhmmomiinigofkjcapegjjndpbikblnp",
    "llcdellnofncikmhimjdbkdjgpmcjbik",
    "imhlianhlhdicjchlbmbfaefhhjencbe",
    "fbgcedjacmlbgleddnoacbnijgmiolem",
    "lphicbbhfmllgmomkkhjfkpbdlncafbn",
    "jjfblogammkiefalfpafidabbnamoknm",
    "jghecgabfgfdldnmbfkhmffcabddioke",
    "ohcpnigalekghcmgcdcenkpelffpdolg",
    "bpconcjcammlapcogcnnelfmaeghhagj",
    "iginnfkhmmfhlkagcmpgofnjhanpmklb",
    "hdhinadidafjejdhmfkjgnolgimiaplp",
    "hiidjliailpkjeigakikbfedlfijngih",
    "cimpffimgeipdhnhjohpbehjkcdpjolg",
    "chlffgpmiacpedhhbkiomidkjlcfhogd",
    "ohahllgiabjaoigichmmfljhkcfikeof",
    "majdfhpaihoncoakbjgbdhglocklcgno",
    "ajphlblkfpppdpkgokiejbjfohfohhmk",
    "nenibigflkdikhamlnekfppbganmojlg",
    "jdogphakondfdmcanpapfahkdomaicfa",
    "dkidoflkcabkfmcpnndogifoldoegnmk",
    "ojplelelocihfchkdaebocpankipadmp",
    "cpaibbcbodhimfnjnakiidgbpiehfgci",
    "ckjefchnfjhjfedoccjbhjpbncimppeg",
    "eaabmejfmdeoaabmealmmbjdjaojakka",
    "bhloflhklmhfpedakmangadcdofhnnoh",
    "pboidikkgjoedgccndgmgcalcpofdoia",
    "oiiaigjnkhngdbnoookogelabohpglmd",
    "ifbdadgbpalmagalacllfaflfakmfkac",
    "nbcojefnccbanplpoffopkoepjmhgdgh",
    "cppjkneekbjaeellbfkmgnhonkkjfpdn",
    "hnmdigodnlhofkojgehfeefbnmfnaodk",
    "emeokgokialpjadjaoeiplmnkjoaegng",
    "omdakjcmkglenbhjadbccaookpfjihpa",
    "jldhpllghnbhlbpcmnajkpdmadaolakh",
    "knheggckgoiihginacbkhaalnibhilkk",
    "pgphcomnlaojlmmcjmiddhdapjpbgeoc",
    "mjnbclmflcpookeapghfhapeffmpodij",
    "noaijdpnepcgjemiklgfkcfbkokogabh",
    "bijihlabcfdnabacffofojgmehjdielb",
    "ncbofnhmmfffmcdmbjfaigepkgmjnlne",
    "ioalpmibngobedobkmbhgmadaphocjdn",
    "phidhnmbkbkbkbknhldmpmnacgicphkf",
    "kjomkjjpbjeennhagfmlahfnlgleecmn",
    "bbafmabaelnnkondpfpjmdklbmfnbmol",
    "fhbohimaelbohpjbbldcngcnapndodjp",
    "oknpjjbmpnndlpmnhmekjpocelpnlfdi",
    "pflmllfnnabikmfkkaddkoolinlfninn",
    "pgpidfocdapogajplhjofamgeboonmmj",
    "noondiphcddnnabmjcihcjfbhfklnnep",
    "cknebhggccemgcnbidipinkifmmegdel",
    "aicmkgpgakddgnaphhhpliifpcfhicfo",
    "kkelicaakdanhinjdeammmilcgefonfh",
    "dogkpdfcklifaemcdfbildhcofnopogp",
    "paijmjmfnjcbjlimjeminlepannmimbi",
    "jlgkpaicikihijadgifklkbpdajbkhjo",
    "pnnfemgpilpdaojpnkjdgfgbnnjojfik",
    "icpgjfneehieebagbmdbhnlpiopdcmna",
    "dbfmnekepjoapopniengjbcpnbljalfg",
    "mciiogijehkdemklbdcbfkefimifhecn",
    "lklfbkdigihjaaeamncibechhgalldgl",
    "ohlencieiipommannpdfcmfdpjjmeolj",
    "epcnnfbjfcgphgdmggkamkmgojdagdnn",
    "mokknliiomknodkdmpcellamkopbdmao",
    "pejdijmoenmkgeppbflobdenhhabjlaj",
    "cfnpidifppmenkapgihekkeednfoenal",
    "jlmilpphhoonfclkcaakafcmkgfalkhl",
    "hhbcihapcmaemjinlbgafnjjihbdmjnf",
    "jedjajddobfbhgoaidfigmlkijbeaene",
    "cmcmennehclgdccnlmnjladhlkmclbkb",
    "bkbdaodnaecdijpajecpncpdomgcoakc",
    "hdppkjifljbdpckfajcmlblbchhledln",
    "fnbdnhhicmebfgdgglcdacdapkcihcoh",
    "eakacpaijcpapndcfffdgphdiccmpknp",
    "dpacanjfikmhoddligfbehkpomnbgblf",
    "mfidniedemcgceagapgdekdbmanojomk",
    "eenflijjbchafephdplkdmeenekabdfb",
    "hmanipjnbjnhoicdnooapcnfonebefel",
    "blipmdconlkpinefehnmjammfjpmpbjk",
    "akdgnmcogleenhbclghghlkkdndkjdjc",
    "llaficoajjainaijghjlofdfmbjpebpa",
    "cjjfaljaaljdjknnmhoajnmgbdcchmpp",
    "ddadgcdmddljmpkpinkalnepdepplpkj",
    "eppiocemhmnlbhjplcgkofciiegomcon",
    "caclkomlalccbpcdllchkeecicepbmbm",
    "djcfdncoelnlbldjfhinnjlhdjlikmph",
    "nemmanchfojaehgkbgcfmdiidbopakpp",
    "pgfbdgicjmhenccemcijooffohcdanic",
    "eojdckfcadamkapabechhbnkleligand",
    "kpiecbcckbofpmkkkdibbllpinceiihk",
    "kcnhkahnjcbndmmehfkdnkjomaanaooo",
    "naklddpomljndpmcpeldoilofefemchb",
    "nlbjncdgjeocebhnmkbbbdekmmmcbfjd",
    "laankejkbhbdhmipfmgcngdelahlfoji",
    "kjacjjdnoddnpbbcjilcajfhhbdhkpgk",
    "kdfieneakcjfaiglcfcgkidlkmlijjnh",
    "jeoacafpbcihiomhlakheieifhpjdfeo",
    "jaoafpkngncfpfggjefnekilbkcpjdgp",
    "nlmmgnhgdeffjkdckmikfpnddkbbfkkk",
    "hkdmdpdhfaamhgaojpelccmeehpfljgf",
    "dgbldpiollgaehnlegmfhioconikkjjh",
    "nlkaejimjacpillmajjnopmpbkbnocid",
    "iogidnfllpdhagebkblkgbfijkbkjdmm",
    "jjckigopagkhaikodedjnmbccfpnmiea",
    "pnlccmojcmeohlpggmfnbbiapkmbliob",
    "kpoecbkildamnnchnlgoboipnblgikpn",
    "nbmoafcmbajniiapeidgficgifbfmjfo",
    "jinjaccalgkegednnccohejagnlnfdag",
    "iliimbpbpliabblllmgebklpjkgeagjp",
    "ndaciljfdnekbnmcpjidoebejglcjidc",
    "inehghpkjjjdgpnagcbogckbonilnidc",
    "ghnomdcacenbmilgjigehppbamfndblo",
    "clmkdohmabikagpnhjmgacbclihgmdje",
    "pnjaodmkngahhkoihejjehlcdlnohgmp",
    "ipdjnhgkpapgippgcgkfcbpdpcgifncb",
    "benjmhnicaokfjhdoolkkjiiccceigdm",
    "fihnjjcciajhdojfnbdddfaoknhalnja",
    "lfkmkidopioccceiemjmndppkadgbmid",
    "gphhapmejobijbbhgpjhcjognlahblep",
    "ejkiikneibegknkgimmihdpcbcedgmpo",
    "idfiabaafjemgcecklpgnebaebonghka",
    "gbiekjoijknlhijdjbaadobpkdhmoebb",
    "dehajjkfchegiinhcmoclkfbnmpgcahj",
    "gamlckmepdclkglolaedeigblmmpmfhf",
    "ekcgkejcjdcmonfpmnljobemcbpnkamh",
    "aejoelaoggembcahagimdiliamlcdmfm",
    "dpplabbmogkhghncfbfdeeokoefdjegm",
    "mmcblfncjaclajmegihojiekebofjcen",
    "mooikfkahbdckldjjndioackbalphokd",
    "mhmphnocemakkjdampibehejoaleebpo",
    "mmnbenehknklpbendgmgngeaignppnbe",
    "fddjpichkajmnkjhcmpbbjdmmcodnkej",
    "dpgjihldbpodlmnjolekemlfbcajnmod",
    "immpkjjlgappgfkkfieppnmlhakdmaab",
    "nnnmhgkokpalnmbeighfomegjfkklkle",
    "icpklikeghomkemdellmmkoifgfbakio",
    "jpcmhcelnjdmblfmjabdeclccemkghjk",
    "opjjpmhoiojifppkkcdabiobhakljdgm",
    "njmehopjdpcckochcggncklnlmikcbnb",
    "ponfpcnoihfmfllpaingbgckeeldkhle",
    "jhhclmfgfllimlhabjkgkeebkbiadflb",
    "cnfianechkepmfdoakelcbamnbfbecke",
    "ailoabdmgclmfmhdagmlohpjlbpffblp",
    "hmffdimoneaieldiddcmajhbjijmnggi",
    "phgddhgfnjjaobkeekohieahfingldac",
    "onomjaelhagjjojbkcafidnepbfkpnee",
    "aikdmpdmpklompbpohmlfjbeohaiholh",
    "ocemooeilogfefcknbhnjlofcfnhohcb",
    "njdniclgegijdcdliklgieicanpmcngj",
    "jjnfhbcilcppomkcmkbbmcadoihkkgah",
    "pbhelknnhilelbnhfpcjlcabhmfangik",
    "okmdknhejjiichkcppoppdaknekjekoa",
    "lapoiohkeidniicbalnfmakkbnpejgbi",
    "gngocbkfmikdgphklgmmehbjjlfgdemm",
    "idgpnmonknjnojddfkpgkljpfnnfcklj",
    "clngdbkpkpeebahjckkjfobafhncgmne",
    "nlhjgcligpbnjphflfdbmabbmjidnmek",
    "mefhakmgclhhfbdadeojlkbllmecialg",
    "cbnaodkpfinfiipjblikofhlhlcickei",
    "iabeihobmhlgpkcgjiloemdbofjbdcic",
    "meajfmicibjppdgbjfkpdikfjcflabpk",
    "cfidkbgamfhdgmedldkagjopnbobdmdn",
    "iakddmmledeclcodpbgebfkhegaaddge",
    "pjbgfifennfhnbkhoidkdchbflppjncb",
    "ajhmfdgkijocedmfjonnpjfojldioehi",
    "pbdpajcdgknpendpmecafmopknefafha",
    "jflaogbiblbidhaogjjagjpjcflipklo",
    "lokadhdaghfjbmailhhenifjejpokche",
    "mkelkmkgljeohnaeehnnkmdpocfmkmmf",
    "migomhggnppjdijnfkiimcpjgnhmnale",
    "acfifjfajpekbmhmjppnmmjgmhjkildl",
    "jnkmfdileelhofjcijamephohjechhna",
    "gecgipfabdickgidpmbicneamekgbaej",
    "baipgmmeifmofkcilhccccoipmjccehn",
    "ceibjdigmfbbgcpkkdpmjokkokklodmc",
    "cgjnhhjpfcdhbhlcmmjppicjmgfkppok",
    "kaoholkoedbpjiangnchpfchhmageifp",
    "gcalenpjmijncebpfijmoaglllgpjagf",
    "hlkenndednhfkekhgcdicdfddnkalmdm",
    "bkhaagjahfmjljalopjnoealnfndnagc",
    "ijkmjnaahlnmdjjlbhbjbhlnmadmmlgg",
    "hfamgdphmadpbopjpnjeclijgabhmeml",
    "dkgjegocmcicmloagcapoglndjkhpdmm",
    "ilkabdcnlaioomjfdafcbkkngcckkilg",
    "bnchicpgbdgahiecgofdabidjihblaff",
    "npflpmeannakjekldamofnldpiefjmmi",
    "bfegaehidkkcfaikpaijcdahnpikhobf",
    "jdanfkhnfpagoijgfmklhgakdicpnfil",
    "nnjjahlikiabnchcpehcpkdeckfgnohf",
    "jiihcciniecimeajcniapbngjjbonjan",
    "ihmgiclibbndffejedjimfjmfoabpcke",
    "cplklnmnlbnpmjogncfgfijoopmnlemp",
    "jnhgnonknehpejjnehehllkliplmbmhn",
    "jpfpebmajhhopeonhlcgidhclcccjcik",
    "gjfpmkejnolcfklaaddjnckanhhgegla",
    "lbfjgknkjfjmnjdgdhbbmmbkoddgpdoc",
    "emngkmlligggbbiioginlkphcmffbncb",
    "lhobafahddgcelffkeicbaginigeejlf",
    "ffbkglfijbcbgblgflchnbphjdllaogb",
    "eljapbgkmlngdpckoiiibecpemleclhh",
    "maekfnoeejhpjfkfmdlckioggdcdofpg",
    "iggpfpnahkgpnindfkdncknoldgnccdg",
    "ljflmlehinmoeknoonhibbjpldiijjmm",
    "dbepggeogbaibhgnhhndojpepiihcmeb",
    "ejfmffkmeigkphomnpabpdabfddeadcb",
    "ppdonaappkjkbgbncmmjencphdclioab",
    "gcoekeoenehjmndhkdnoomdjeaclkhbe",
    "hcfnhafpadfnabbnjnhdfdacolpmdbjo",
    "noaflfgdoindheknalgiekgjlfdecogn",
    "nnnkddnnlpamobajfibfdgfnbcnkgngh",
    "eebnbmbhdfnfhfhigoklhaklkodghbla",
    "cdonnmffkdaoajfknoeeecmchibpmkmg",
    "chlmfnfjlieaejfpcgjkkillpnllmiai",
    "jkncabbipkgbconhaajbapbhokpbgkdc",
    "lhgiigkiddoalobhmmcpdhddlccindjj",
    "ddaloccgjfibfpkalenodgehlhkgoahe",
    "lmnganadkecefnhncokdlaohlkneihio",
    "okjdbeegldeilceaflghgfdemobmfhbd",
    "pjhnilfooknlkdonmjnleaomamfehkli",
    "cdochbecpfdpjobpgnacnbepkgcfhoek",
    "gginmiamniniinhbipmknjiefidjlnob",
    "bldgenmjegcnjebiongilahhcjldgmlm",
    "plmndhfiofdlcgahoinehedbincopilm",
    "oligonmocnihangdjlloenpndnniikol",
    "kkepemkdiboiecpjlmdmighjkmfokbpm",
    "gdkddcndonbadjjminbeeokgcknciebo",
    "ofoeigeaodhbjogdigckajfhjbonaofg",
    "gefpceefdmmojbgmfmnkeanmpclobjgj",
    "cgdjpilhipecahhcilnafpblkieebhea",
    "bfogiafebfohielmmehodmfbbebbbpei",
    "kogfdlbehkaeoafmgaecphlnhohpabig",
    "lpognpnpncelknkahlngpojfjgdmkodn",
    "hnlkiofnhhoahaiimdicppgemmmomijo",
    "kbpnbonnhilfdihhodnflcplajklibbc",
    "hojhhmecfdlobchoejlbonoabacfnaap",
    "jlpenjcbjaocajkajjklmfomhohiodfa",
    "pfjibkklgpfcfdlhijfglamdnkjnpdeg",
    "hgmhmanijnjhaffoampdlllchpolkdnj",
    "nfdfiepdkbnoanddpianalelglmfooik",
    "nfphpgdlkoindbccbdmilopgeafllemo",
    "pgbllmbdjgcalkoimdfcpknbjgnhjclg",
    "jfchnphgogjhineanplmfkofljiagjfb",
    "nabbmpekekjknlbkgpodfndbodhijjem",
    "fmidkjgknpkbmninbmklhcgaalfalbdh",
    "aefehdhdciieocakfobpaaolhipkcpgc",
    "akimgimeeoiognljlfchpbkpfbmeapkh",
    "eekailopagacbcdloonjhbiecobagjci",
    "iodihamcpbpeioajjeobimgagajmlibd",
    "kfnnoammpigcglgbhcbbdpnekbcddahe",
    "gbgjpdhhnbgmnafojckjmjogcpoinlim",
    "djnhkfljnimcpelfndpcjcgngmefaobl",
    "fakegmdomhmegokfomgmkbopjibonfcp",
    "ljfidlkcmdmmibngdfikhffffdmphjae",
    "fbcgkphadgmbalmlklhbdagcicajenei",
    "npgcnondjocldhldegnakemclmfkngch",
    "jffafkigfgmjafhpkoibhfefeaebmccg",
    "lcnhdebfcdfbifgkkofhmalbiglindgi",
    "digojkgonhgmnohbapdfjllpnmjmdhpg",
    "cjdnfmjmdligcpfcekfmenlhiopehjkd",
    "cmkdbmfndkfgebldhnkbfhlneefdaaip",
    "eadndfjplgieldjbigjakmdgkmoaaaoc",
    "dapjbgnjinbpoindlpdmhochffioedbn",
    "mlikepnkghhlnkgeejmlkfeheihlehne",
    "pbeheebcldakpkohnellphloljkaanfa",
    "ajmecfihhnibjmmihpecefjjckgbmedh",
    "hafdlehgocfcodbgjnpecfajgkeejnaa",
    "kpbnombpnpcffllnianjibmpadjolanh",
    "phfkifnjcmdcmljnnablahicoabkokbg",
    "gnblbpbepfbfmoobegdogkglpbhcjofh",
    "mjjgmlmpeaikcaajghilhnioimmaibon",
    "olimcenppncifgiahopimblidefpdffi",
    "eagiakjmjnblliacokhcalebgnhellfi",
    "ngceodoilcgpmkijopinlkmohnfifjfb",
    "hddnkoipeenegfoeaoibdmnaalmgkpip",
    "dhheiegalgcabbcobinipgmhepkkeidk",
    "onhiacboedfinnofagfgoaanfedhmfab",
    "mjgcgnfikekladnkhnimljcalfibijha",
    "cbhilkcodigmigfbnphipnnmamjfkipp",
    "jdbnofccmhefkmjbkkdkfiicjkgofkdh",
    "dkfhfaphfkopdgpbfkebjfcblcafcmpi",
    "eignhdfgaldabilaaegmdfbajngjmoke",
    "hkhggnncdpfibdhinjiegagmopldibha",
    "oejgccbfbmkkpaidnkphaiaecficdnfn",
    "glcipcfhmopcgidicgdociohdoicpdfc",
    "hipncndjamdcmphkgngojegjblibadbe",
    "oiecklaabeielolbliiddlbokpfnmhba",
    "jdopnakmnlnccgpfpmjmdjjohmcdgabp",
    "iplffkdpngmdjhlpjmppncnlhomiipha",
    "dicgkflojhbopmagcacdklcpdfdcnhko",
    "cmllgdnjnkbapbchnebiedipojhmnjej",
    "ibnejdfjmmkpcnlpebklmnkoeoihofec",
    "oohkbdinpdepmoabgkegakmecgomibef",
    "oodfdmglhbbkkcngodjjagblikmoegpa",
    "jkompbllimaoekaogchhkmkdogpkhojg",
    "bafijghppfhdpldihckdcadbcobikaca",
    "dfnhijmficoiilogkjlnkionfjlgecdi",
    "bckjlihkmgolmgkchbpiponapgjenaoa",
    "kiapnojckdhnfpjpdgbneaioggjgooga",
    "gpaiobkfhnonedkhhfjpmhdalgeoebfa",
    "ljfcfconehlpojiodgopbcefmkfmfabd",
    "fpdnjdlbdmifoocedhkighhlbchbiikl",
    "cnlogloeabhinechhmcgkkgglmiefaif",
    "jmegndhbalhkegdidohofafobbcabine",
    "feolagkacappiaieohahjkeaikhjjcfa",
    "dbjbempljhcmhlfpfacalomonjpalpko",
    "afpbjjgbdimpioenaedcjgkaigggcdpp",
    "oaobmlmjmhedmlphfdmdjpppjmcljnkp",
    "dcdfjddkdjkaohjceimnbgniajaholfl",
    "kohfgcgbkjodfcfkcackpagifgbcmimk",
    "jfiihjeimjpkpoaekpdpllpaeichkiod",
    "ijejnggjjphlenbhmjhhgcdpehhacaal",
    "gjedkhmeelbomjafdlehdcomjhobcnbk",
    "lcipembjfkmeggpihdpdgnjildgniffl",
    "ibefaeehajgcpooopoegkifhgecigeeg",
    "dhikfimimcjpoaliefjlffaebdeomeni",
    "nmdhbmdklokcmpmcegmbfehjencmbeab",
    "pllcidbcfbamjfbfpemnnjohnfcliakf",
    "njgehaondchbmjmajphnhlojfnbfokng",
    "jajilbjjinjmgcibalaakngmkilboobh",
    "aopfgjfeiimeioiajeknfidlljpoebgc",
    "mfedioikeigljhjfpghdejnogniddhna",
    "dpjamkmjmigaoobjbekmfgabipmfilij",
    "kekahkplibinaibelipdcikofmedafmb",
    "blljobffcekcbopmkgfhpcjmbfnelkfg"
]

def download_benign_dataset(count=250):
    print(f"Downloading {count} benign extensions...")
    os.makedirs(settings.RAW_BENIGN_DIR, exist_ok=True)
    
    success = 0
    # First count how many are already downloaded
    for ext_id in POPULAR_EXTENSIONS:
        output_path = os.path.join(settings.RAW_BENIGN_DIR, f"{ext_id}.crx")
        if os.path.exists(output_path):
            success += 1

    print(f"Already have {success} downloaded benign extensions.")
    
    if success >= count:
        print(f"Already reached target of {count} benign extensions.")
        return

    # Iterate through all popular extensions to download more
    pbar = tqdm(total=count, initial=success, desc="Downloading Benign Extensions")
    for ext_id in POPULAR_EXTENSIONS:
        if success >= count:
            break
        output_path = os.path.join(settings.RAW_BENIGN_DIR, f"{ext_id}.crx")
        if os.path.exists(output_path):
            continue
        if download_crx(ext_id, settings.RAW_BENIGN_DIR):
            success += 1
            pbar.update(1)
            
    pbar.close()
    print(f"Successfully compiled {success} extensions in {settings.RAW_BENIGN_DIR}")

if __name__ == "__main__":
    download_benign_dataset(250)
