/**
 * List of people named in the Epstein files.
 * Each entry has:
 *   - name:   display name to search for in page text
 *   - anchor: fragment identifier on the Wikipedia article
 *
 * Wikipedia article:
 * https://en.wikipedia.org/wiki/List_of_people_named_in_the_Epstein_files
 */
const EPSTEIN_LIST = [
  { name: "Woody Allen", anchor: "Woody_Allen" },
  { name: "Anil Ambani", anchor: "Anil_Ambani" },
  { name: "Eva Andersson-Dubin", anchor: "Eva_Andersson-Dubin" },
  { name: "Dan Ariely", anchor: "Dan_Ariely" },
  { name: "Peter Attia", anchor: "Peter_Attia" },
  { name: "José María Aznar", anchor: "Jos%C3%A9_Mar%C3%ADa_Aznar" },
  { name: "Joscha Bach", anchor: "Joscha_Bach" },
  { name: "Doug Band", anchor: "Doug_Band" },
  { name: "Steve Bannon", anchor: "Steve_Bannon" },
  { name: "Ehud Barak", anchor: "Ehud_Barak" },
  { name: "Tom Barrack", anchor: "Tom_Barrack" },
  { name: "Sergei Belyakov", anchor: "Sergei_Belyakov" },
  { name: "Leon Black", anchor: "Leon_Black" },
  { name: "David Blaine", anchor: "David_Blaine" },
  { name: "Todd Boehly", anchor: "Todd_Boehly" },
  { name: "Leon Botstein", anchor: "Leon_Botstein" },
  { name: "Ana Botella", anchor: "Ana_Botella" },
  { name: "Edward Boyden", anchor: "Edward_Boyden" },
  { name: "Richard Branson", anchor: "Richard_Branson" },
  { name: "Børge Brende", anchor: "B%C3%B8rge_Brende" },
  { name: "Flavio Briatore", anchor: "Flavio_Briatore" },
  { name: "Sergey Brin", anchor: "Sergey_Brin" },
  { name: "John Brockman", anchor: "John_Brockman" },
  { name: "David Brooks", anchor: "David_Brooks" },
  { name: "Jean-Luc Brunel", anchor: "Jean-Luc_Brunel" },
  { name: "William Burns", anchor: "William_Burns" },
  { name: "Naomi Campbell", anchor: "Naomi_Campbell" },
  { name: "Nick Candy", anchor: "Nick_Candy" },
  { name: "Fidel Castro", anchor: "Fidel_Castro" },
  { name: "Frédéric Chaslin", anchor: "Fr%C3%A9d%C3%A9ric_Chaslin" },
  { name: "Noam Chomsky", anchor: "Noam_Chomsky" },
  { name: "Deepak Chopra", anchor: "Deepak_Chopra" },
  { name: "George Church", anchor: "George_Church" },
  { name: "Vitaly Churkin", anchor: "Vitaly_Churkin" },
  { name: "Bill Clinton", anchor: "Bill_Clinton" },
  { name: "David Copperfield", anchor: "David_Copperfield" },
  { name: "Bill Cosby", anchor: "Bill_Cosby" },
  { name: "Richard Dawkins", anchor: "Richard_Dawkins" },
  { name: "Alan Dershowitz", anchor: "Alan_Dershowitz" },
  { name: "Maria Drokova", anchor: "Maria_Drokova" },
  { name: "Glenn Dubin", anchor: "Glenn_Dubin" },
  { name: "Andrew Farkas", anchor: "Andrew_Farkas" },
  { name: "Sarah Ferguson", anchor: "Sarah_Ferguson" },
  { name: "Bill Gates", anchor: "Bill_Gates" },
  { name: "David Gelernter", anchor: "David_Gelernter" },
  { name: "Joe Gibbs", anchor: "Joe_Gibbs" },
  { name: "Tenzin Gyatso", anchor: "Tenzin_Gyatso" },
  { name: "Jonathan Haidt", anchor: "Jonathan_Haidt" },
  { name: "Josh Harris", anchor: "Josh_Harris" },
  { name: "Sam Harris", anchor: "Sam_Harris" },
  { name: "Stephen Hawking", anchor: "Stephen_Hawking" },
  { name: "Reid Hoffman", anchor: "Reid_Hoffman" },
  { name: "Jack Horner", anchor: "Jack_Horner" },
  { name: "Joi Ito", anchor: "Joi_Ito" },
  { name: "Michael Jackson", anchor: "Michael_Jackson" },
  { name: "Thorbjørn Jagland", anchor: "Thorbj%C3%B8rn_Jagland" },
  { name: "Jay-Z", anchor: "Jay-Z" },
  { name: "John de Jongh Jr.", anchor: "John_de_Jongh_Jr." },
  { name: "Nicole Junkermann", anchor: "Nicole_Junkermann" },
  { name: "Mona Juul", anchor: "Mona_Juul" },
  { name: "Dean Kamen", anchor: "Dean_Kamen" },
  { name: "Brad S. Karp", anchor: "Brad_S._Karp" },
  { name: "Brett Kavanaugh", anchor: "Brett_Kavanaugh" },
  { name: "Robert F. Kennedy Jr.", anchor: "Robert_F._Kennedy_Jr." },
  { name: "Jeff Koons", anchor: "Jeff_Koons" },
  { name: "Stephen Kosslyn", anchor: "Stephen_Kosslyn" },
  { name: "Bobby Kotick", anchor: "Bobby_Kotick" },
  { name: "Lawrence Krauss", anchor: "Lawrence_Krauss" },
  { name: "Miroslav Lajčák", anchor: "Miroslav_Laj%C4%8D%C3%A1k" },
  { name: "Guy Laliberté", anchor: "Guy_Lalibert%C3%A9" },
  { name: "Mark Landon", anchor: "Mark_Landon" },
  { name: "Caroline Lang", anchor: "Caroline_Lang" },
  { name: "Jack Lang", anchor: "Jack_Lang" },
  { name: "Ronald Lauder", anchor: "Ronald_Lauder" },
  { name: "Sergey Lavrov", anchor: "Sergey_Lavrov" },
  { name: "Howard Lutnick", anchor: "Howard_Lutnick" },
  { name: "Peter Mandelson", anchor: "Peter_Mandelson" },
  { name: "Nadia Marcinko", anchor: "Nadia_Marcinko" },
  { name: "Ashley Massaro", anchor: "Ashley_Massaro" },
  { name: "Ghislaine Maxwell", anchor: "Ghislaine_Maxwell" },
  { name: "Robert Maxwell", anchor: "Robert_Maxwell" },
  { name: "Mette-Marit", anchor: "Mette-Marit" },
  { name: "Marvin Minsky", anchor: "Marvin_Minsky" },
  { name: "George J. Mitchell", anchor: "George_J._Mitchell" },
  { name: "Mohammed bin Salman", anchor: "Mohammed_bin_Salman" },
  { name: "Andrew Mountbatten-Windsor", anchor: "Andrew_Mountbatten-Windsor" },
  { name: "Prince Andrew", anchor: "Andrew_Mountbatten-Windsor" },
  { name: "Robert Mugabe", anchor: "Robert_Mugabe" },
  { name: "Elon Musk", anchor: "Elon_Musk" },
  { name: "Kimbal Musk", anchor: "Kimbal_Musk" },
  { name: "Nathan Myhrvold", anchor: "Nathan_Myhrvold" },
  { name: "Mira Nair", anchor: "Mira_Nair" },
  { name: "Annabelle Neilson", anchor: "Annabelle_Neilson" },
  { name: "Elisa New", anchor: "Elisa_New" },
  { name: "Boris Nikolic", anchor: "Boris_Nikolic" },
  { name: "Martin Nowak", anchor: "Martin_Nowak" },
  { name: "Hans Ulrich Obrist", anchor: "Hans_Ulrich_Obrist" },
  { name: "Mehmet Oz", anchor: "Mehmet_Oz" },
  { name: "Andrés Pastrana Arango", anchor: "Andr%C3%A9s_Pastrana_Arango" },
  { name: "Jean Pigozzi", anchor: "Jean_Pigozzi" },
  { name: "Steven Pinker", anchor: "Steven_Pinker" },
  { name: "John Phelan", anchor: "John_Phelan" },
  { name: "Stacey Plaskett", anchor: "Stacey_Plaskett" },
  { name: "Christopher Poole", anchor: "Christopher_Poole" },
  { name: "Soon-Yi Previn", anchor: "Soon-Yi_Previn" },
  { name: "Penny Pritzker", anchor: "Penny_Pritzker" },
  { name: "Thomas Pritzker", anchor: "Thomas_Pritzker" },
  { name: "Hardeep Singh Puri", anchor: "Hardeep_Singh_Puri" },
  { name: "Pusha T", anchor: "Pusha_T" },
  { name: "Vladimir Putin", anchor: "Vladimir_Putin" },
  { name: "Joshua Cooper Ramo", anchor: "Joshua_Cooper_Ramo" },
  { name: "Lisa Randall", anchor: "Lisa_Randall" },
  { name: "Brett Ratner", anchor: "Brett_Ratner" },
  { name: "Terje Rød-Larsen", anchor: "Terje_R%C3%B8d-Larsen" },
  { name: "David A. Ross", anchor: "David_A._Ross" },
  { name: "Ariane de Rothschild", anchor: "Ariane_de_Rothschild" },
  { name: "Lynn Forester de Rothschild", anchor: "Lynn_Forester_de_Rothschild" },
  { name: "Marc Rowan", anchor: "Marc_Rowan" },
  { name: "Kevin Rudd", anchor: "Kevin_Rudd" },
  { name: "Kathryn Ruemmler", anchor: "Kathryn_Ruemmler" },
  { name: "David Schoen", anchor: "David_Schoen" },
  { name: "Al Seckel", anchor: "Al_Seckel" },
  { name: "Andres Serrano", anchor: "Andres_Serrano" },
  { name: "Karyna Shuliak", anchor: "Karyna_Shuliak" },
  { name: "Peggy Siegal", anchor: "Peggy_Siegal" },
  { name: "Princess Sofia", anchor: "Princess_Sofia" },
  { name: "Kevin Spacey", anchor: "Kevin_Spacey" },
  { name: "Jes Staley", anchor: "Jes_Staley" },
  { name: "Ken Starr", anchor: "Ken_Starr" },
  { name: "David Stern", anchor: "David_Stern" },
  { name: "Sultan Ahmed bin Sulayem", anchor: "Sultan_Ahmed_bin_Sulayem" },
  { name: "Lawrence H. Summers", anchor: "Lawrence_H._Summers" },
  { name: "David Tang", anchor: "David_Tang" },
  { name: "Corina Tarnita", anchor: "Corina_Tarnita" },
  { name: "Peter Thiel", anchor: "Peter_Thiel" },
  { name: "Amanda Thirsk", anchor: "Amanda_Thirsk" },
  { name: "Jess Ting", anchor: "Jess_Ting" },
  { name: "Steve Tisch", anchor: "Steve_Tisch" },
  { name: "Jean Todt", anchor: "Jean_Todt" },
  { name: "Mark Tramo", anchor: "Mark_Tramo" },
  { name: "Robert Trivers", anchor: "Robert_Trivers" },
  { name: "Donald J. Trump", anchor: "Donald_Trump" },
  { name: "President Trump", anchor: "Donald_Trump" },
  { name: "Donald Trump", anchor: "Donald_Trump" },
  { name: "Donald Trump Jr.", anchor: "Donald_Trump_Jr." },
  { name: "Eric Trump", anchor: "Eric_Trump" },
  { name: "Melania Trump", anchor: "Melania_Trump" },
  { name: "Paul Tweed", anchor: "Paul_Tweed" },
  { name: "Brian Vickers", anchor: "Brian_Vickers" },
  { name: "Karim Wade", anchor: "Karim_Wade" },
  { name: "Michael Waltrip", anchor: "Michael_Waltrip" },
  { name: "Casey Wasserman", anchor: "Casey_Wasserman" },
  { name: "Harvey Weinstein", anchor: "Harvey_Weinstein" },
  { name: "Les Wexner", anchor: "Les_Wexner" },
  { name: "Nathan Wolfe", anchor: "Nathan_Wolfe" },
  { name: "Michael Wolff", anchor: "Michael_Wolff" },
  { name: "Mark Zuckerberg", anchor: "Mark_Zuckerberg" },
  { name: "Jacob Zuma", anchor: "Jacob_Zuma" },
];

/**
 * Case-sensitive names — these are matched with exact casing only.
 * Used for short/generic words like "Trump" that would false-positive
 * if matched case-insensitively (e.g. "trump card").
 */
const EPSTEIN_LIST_CASE_SENSITIVE = [
  { name: "Trump", anchor: "Donald_Trump" },
];
